### ISSUE TITLE
Zombies pick up graves

### ISSUE THREAD

**Issue by Alrawn** [M4thG33k/TombManyGraves#6] opened 2016-06-23 12:14 UTC
I just walked to a location that another player had just died at and came upon a zombie carrying a Player Grave (he dropped it on kill, I could pick it up). The players grave was intact and working, so I guess the zombie must have picked the block up somehow.

**Comment by M4thG33k** [comment] 2016-06-23 12:18
Yeah, there's a weird issue of grave blocks being dropped when a player dies via explosion. I'm still trying to narrow down the cause of the issue, but as a temporary fix I made sure that the graves cannot be placed in the world from your hand (and are easily able to be deleted by simply throwing it out of your inventory similarly to the inventory lists).

**Comment by M4thG33k** [comment] 2016-06-23 14:24
I think the next version may have a potential fix for this

**Comment by M4thG33k** [comment] 2016-07-16 22:39
If nobody is able to reproduce this issue with the newest version within the week, I am going to close this.

**Closed as completed** 2016-09-21 14:15 UTC
